services:
  app:
    image: ghcr.io/codebykenth/trading-journal-v2:staging
    container_name: tradexy_app_staging
    restart: unless-stopped
    working_dir: /var/www
    env_file: .env
    environment:
      - TZ=Asia/Manila
    volumes:
      - app_storage_staging:/var/www/storage
      - app_public_staging:/var/www/public-shared
    networks:
      - tradexy_staging

  nginx:
    image: nginx:alpine
    container_name: tradexy_nginx_staging
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:80"
    volumes:
      - app_public_staging:/var/www/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - tradexy_staging

  queue:
    image: ghcr.io/codebykenth/trading-journal-v2:staging
    container_name: tradexy_queue_staging
    restart: unless-stopped
    working_dir: /var/www
    env_file: .env
    environment:
      - TZ=Asia/Manila
    volumes:
      - app_storage_staging:/var/www/storage
    depends_on:
      - app
    networks:
      - tradexy_staging
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600

  reverb:
    image: ghcr.io/codebykenth/trading-journal-v2:staging
    container_name: tradexy_reverb_staging
    restart: unless-stopped
    working_dir: /var/www
    env_file: .env
    environment:
      - TZ=Asia/Manila
    depends_on:
      - app
    networks:
      - tradexy_staging
    command: php artisan reverb:start --host="0.0.0.0" --port=8080
networks:
  tradexy_staging:

volumes:
  app_storage_staging:
  app_public_staging: