services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.prod
    container_name: tradexy_app_staging
    restart: unless-stopped
    working_dir: /var/www
    networks:
      - tradexy_staging

  nginx:
    image: nginx:alpine
    container_name: tradexy_nginx_staging
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./public:/var/www/public:ro
      - ./storage/app/public:/var/www/storage/app/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - tradexy_staging

networks:
  tradexy_staging: