<x-layouts.app title="Terms and Conditions | Tradexy">
    <div class="max-w-4xl mx-auto px-6 py-12 lg:py-24">
        <h1 class="text-3xl md:text-5xl font-bold text-gray-900 dark:text-white mb-8">Terms and Conditions</h1>
        
        <div class="prose dark:prose-invert prose-blue max-w-none space-y-8 text-gray-600 dark:text-gray-400">
            <section>
                <h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-4">1. Acceptance of Terms</h2>
                <p>By accessing and using Tradexy ("the Platform"), you agree to be bound by these Terms and Conditions. If you do not agree, please do not use the Platform.</p>
            </section>

            <section>
                <h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-4">2. Description of Service</h2>
                <p>Tradexy is a trading journal and analytical tool designed to help users log, track, and analyze their trading activities. The platform may include automated data fetching, AI-generated market news, and account balance monitoring.</p>
            </section>

            <section class="bg-blue-50 dark:bg-blue-900/10 p-6 rounded-xl border border-blue-100 dark:border-blue-900/30">
                <h2 class="text-xl font-bold text-blue-900 dark:text-blue-300 mb-4">3. NO FINANCIAL ADVICE</h2>
                <p class="font-medium text-blue-800 dark:text-blue-400 italic">IMPORTANT: Tradexy is a documentation and analysis tool only.</p>
                <ul class="list-disc ml-6 mt-4 space-y-2">
                    <li>The information provided on the Platform, including AI-powered market summaries and trade analysis, is for educational and logging purposes only.</li>
                    <li>Tradexy does not provide financial, investment, or trading advice.</li>
                    <li>Any trading decisions you make are solely your own responsibility. Tradexy is not liable for any financial losses incurred from your trading activities.</li>
                </ul>
            </section>

            <section>
                <h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-4">4. User Accounts and Security</h2>
                <ul class="list-disc ml-6 space-y-2">
                    <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
                    <li>You agree to notify us immediately of any unauthorized use of your account.</li>
                    <li>We use redundant storage and secure database technologies (Neon) for your journal data, and isolated file storage (Firebase) for your trade screenshots.</li>
                </ul>
            </section>

            <section>
                <h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-4">5. Third-Party Integrations</h2>
                <p>Tradexy integrates with various third-party services (e.g., Firebase Storage for your charts, Neon for database infrastructure). Your use of these services is governed by their respective privacy policies.</p>
            </section>

            <section>
                <h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-4">5. AI-Generated Content</h2>
                <p>Market news and trade analysis generated by AI are subject to "hallucinations" or inaccuracies. You should never rely solely on AI-generated content for time-sensitive financial decisions.</p>
            </section>

            <section>
                <h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-4">6. Limitation of Liability</h2>
                <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, TRADEXY SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF YOUR USE OF THE PLATFORM, INCLUDING BUT NOT LIMITED TO TRADING LOSSES, DATA LOSS, OR SYSTEM DOWNTIME.</p>
            </section>

            <section class="pt-8 border-t border-gray-200 dark:border-gray-800">
                <p class="text-sm">Last updated: March 21st, 2026</p>
            </section>
        </div>
    </div>
</x-layouts.app>
